In [1]:
import numpy as np
from numpy import array
import scipy.linalg

# example array a 
a = np.array([[[1],[2],[3]],[[4],[5],[6]]]) # multi-dimentional array literal
b= np.matrix("[1,2,3 ; 4,5,6]") # matrix literal
c1 = array([1,2,3])
c2 = array([4,5,6])
d = np.random.randint(0,100,[3,5]) # random 3*5 matrix
A = np.random.randint(1,10,[3,3])
x = [1,2,3]
B = A@x

In [2]:
print(np.ndim(a)) # num of dims
print(a.ndim)
print()
print(np.size(a)) # num of elements
print(a.size)
print()
print(np.shape(b)) # size of matrix
print(b.shape)
print()
print(a.shape[3-1]) # num of elemets of n-th dim of array
print()
c=np.block([[c1],[c2]])
print(c) # construct matrix from blocks
print()
print(c1[-1]) # last elemet of 1*n matrix c1
print()
print(c[1,2]) # access elemet at (row 2, col 3)
print()
print(c[0]) # entire first row
print()
print(c[0:2]) # entire first two row
print()
print(c[-2:]) # entire last two row
print()
print(d)
print(d[np.ix_([0,2],[0,1,3])]) # elements across row 1,3 and col 1,2,4
print(d[:,0:4:2]) # every other cols from col1 to col 5
print(d[:,::-1]) # reverse col order
print(d[np.r_[:len(d),1]]) # copy row two and append to the end


3
3

6
6

(2, 3)
(2, 3)

1

[[1 2 3]
 [4 5 6]]

3

6

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

[[85  2  9 46  4]
 [64  7 41  3 97]
 [53 14 87  7 63]]
[[85  2 46]
 [53 14  7]]
[[85  9]
 [64 41]
 [53 87]]
[[ 4 46  9  2 85]
 [97  3 41  7 64]
 [63  7 87 14 53]]
[[85  2  9 46  4]
 [64  7 41  3 97]
 [53 14 87  7 63]
 [64  7 41  3 97]]


In [3]:
print(c.T) # Transpose
print(c.conj().T) # conjugate transpose
print()
print(c@c1) # matrix multiply
print(c1*c) # element-wise multiply
print(c*6/c1) # element-wise divide
print(c**2) # element-wise exponentiation
print()
print((c>3)) # logic greater than
print(np.nonzero(c>3)) # index of elements greater than 3
print(c[:,np.nonzero(c1>2)[0]]) # extract the col of c where c1>2
print(c[:,c1.T>2]) # extrace col of c there c1.T>2
e = c.copy() # numpy assigns by reference
e[e<2] = 0 # zero out elements smaller than 2
print(e)
print()
f = c[1,:].copy() # numpy slices are by reference
print(f)
print()
g=c.flatten() # turn array into vector (forces a copy)
print(g)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]

[14 32]
[[ 1  4  9]
 [ 4 10 18]]
[[ 6.  6.  6.]
 [24. 15. 12.]]
[[ 1  4  9]
 [16 25 36]]

[[False False False]
 [ True  True  True]]
(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))
[[3]
 [6]]
[[3]
 [6]]
[[0 2 3]
 [4 5 6]]

[4 5 6]

[1 2 3 4 5 6]


In [4]:
print(np.arange(1.,11.)) # create an increasing vector
print(np.r_[1. : 11])
print(np.r_[1.:10.:10j])
print(np.arange(10.))
print(np.r_[:10.])
print(np.r_[:9:10j])
print(np.arange(1.,11.)[:,np.newaxis]) # create an increase col
print()
print(np.zeros((3,4))) # create 3*4 zero array
print(np.zeros((3,4,5))) # 3*4*5 zero array
print()
print(np.ones((3,4))) # create 3*4 two dim array full of 64 bit floating point ones
print()
print(np.eye(3)) # 3*3 identity matrix
print(np.diag(c1)) # diagonal matrix of c1
print(np.diag(c1,1)) # diagonal matrix, diagonal above the main diagonal
print()
print(np.linspace(1,3,4)) # 4 equally spaced samples between 1 and 3

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]

[1.         1.66666667 2.33333333 3.        ]


In [5]:
print(np.mgrid[0:9.,0:6.]) # 2D arrays: one of x values, the other of y values
print(np.meshgrid(np.r_[0:9.],np.r_[0:6.]))
print(np.ogrid[0:9.,0:6]) # best way to eval functions on a grid
print(np.ix_(np.r_[0:9.],np.r_[0:6.]))
print()
print(np.meshgrid([1,2,4],[2,4,5]))
print(np.ix_([1,2,4],[2,4,5]))

[[[0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1.]
  [2. 2. 2. 2. 2. 2.]
  [3. 3. 3. 3. 3. 3.]
  [4. 4. 4. 4. 4. 4.]
  [5. 5. 5. 5. 5. 5.]
  [6. 6. 6. 6. 6. 6.]
  [7. 7. 7. 7. 7. 7.]
  [8. 8. 8. 8. 8. 8.]]

 [[0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]]]
[array([[0., 1., 2., 3., 4., 5., 6., 7., 8.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8.]]), array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.]])]
[array([[0.],
       [1.],
       [2.],
       [3.],
  

In [6]:
print(np.tile(c,(2,3))) # create a 2*3 copy of c
print()
print(np.concatenate((c,e),1)) # concatenate c and e
print(np.hstack((c,e)))
print(np.column_stack((c,e)))
print(np.c_[c,e])
print(np.concatenate((c,e))) # concatenate rows of c and e
print(np.vstack((c,e)))
print(np.r_[c,e])

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]

[[1 2 3 0 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 0 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 0 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 0 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [0 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [0 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [0 2 3]
 [4 5 6]]


In [7]:
print(c.max()) # return the maximum element of c
print(c.max(0)) # return the maximum element of each col of matrix c
print(c.max(1)) # return the maximum element of each row of matrix c
print(np.maximum(c,e)) 
# compare c and e element-wise, and return the maximum value from each pair
print()
print(np.sqrt(c1@c1)) # L2 norm
print(np.linalg.norm(c1))
print()
print(np.logical_and(c,e)) # element-wise AND operator
print(c&e) # bitwise AND operator
print(c|e) # bitwise OR operator

6
[4 5 6]
[3 6]
[[1 2 3]
 [4 5 6]]

3.7416573867739413
3.7416573867739413

[[False  True  True]
 [ True  True  True]]
[[0 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [8]:
print(np.linalg.inv(np.vstack((c,c1-0.5)))) # inverse of square matrix
print(np.linalg.pinv(c)) # pseudo-inverse of matrix c
print()
print(np.linalg.matrix_rank(c)) # matrix rank of array c
print()
print(np.linalg.solve(A,B)) # solve for x in Ax=B (when A is square)
print(np.linalg.lstsq(A,B,rcond=None)) # solve for x in Ax=B (when A is not square) 
# multilinear regression
print(np.linalg.solve(A.T,B.T)) # solve for x in xA=B
print()
U,S,Vh = np.linalg.svd(A) # SVD
V = Vh.T
print ("U =",U,"\n","S =",S,"\n", "V=", V)
print()
print(np.linalg.cholesky([[2,-1],[-1,2]]).T) # cholesky facterization
print()
D,V = np.linalg.eig(A) # eigen decomposition
print("D =",D,"\n V =",V)
print()
Q,R = scipy.linalg.qr(A) # QR decomposition
print("Q =",Q,"\n R =",R)
print()
L1,U1,P = scipy.linalg.lu(A) # LU decomposition
print("L =",L1,"\n U =",U1,"\n P =",P)
print()
import scipy.sparse.linalg
print(scipy.sparse.linalg.cg(A,B)) # conjugate gradients solver

[[ 1.2009599e+16 -1.7156570e+15 -1.0293942e+16]
 [-2.4019198e+16  3.4313140e+15  2.0587884e+16]
 [ 1.2009599e+16 -1.7156570e+15 -1.0293942e+16]]
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]

2

[1. 2. 3.]
(array([1., 2., 3.]), array([], dtype=float64), 3, array([12.31814763,  4.68371638,  2.0799134 ]))
[ 4.4 -3.6  6. ]

U = [[-0.73015613 -0.24823162 -0.63659492]
 [-0.60516859 -0.19763373  0.77117565]
 [-0.31724281  0.94832588 -0.0059185 ]] 
 S = [12.31814763  4.68371638  2.0799134 ] 
 V= [[-0.36348984  0.35322749 -0.86203566]
 [-0.39470481  0.77977927  0.48595515]
 [-0.84385025 -0.51688938  0.14402125]]

[[ 1.41421356 -0.70710678]
 [ 0.          1.22474487]]

D = [10.85138716  2.19246841 -5.04385557] 
 V = [[-0.70969626 -0.84943054 -0.48906736]
 [-0.51703983  0.52417717 -0.53720734]
 [-0.47854052  0.06087727  0.68718366]]

Q = [[-0.78446454  0.57735027 -0.22645541]
 [-0.19611614 -0.57735027 -0.79259392]
 [-0.58834841 -0.57735027  0.56613852]] 
 R = 

In [9]:
print(np.fft.fft(c1)) # Fourier trans
print(np.fft.ifft(np.fft.fft(c1))) # inverse Fourier trans
print()
print(np.sort(A)) # sort a matrix
A.sort()
print(A)
print()
I = np.argsort(A[:,2]) # sort one row at a time
b=A[2,:]
print(b)
print()
import scipy.signal
scipy.signal.resample(A.flatten(),int(len(A.flatten())/2)) # downsample
print()
print(np.unique(A)) # find unique elements in A
print()
print(a.shape)
print(np.squeeze(a,axis=2)) # squeeze the dim with dim = 1 

[ 6. +0.j        -1.5+0.8660254j -1.5-0.8660254j]
[1.+0.j 2.+0.j 3.+0.j]

[[2 4 8]
 [1 3 7]
 [1 3 5]]
[[2 4 8]
 [1 3 7]
 [1 3 5]]

[1 3 5]


[1 2 3 4 5 7 8]

(2, 3, 1)
[[1 2 3]
 [4 5 6]]
